// moon: The build system and package manager for MoonBit.
// Copyright (C) 2024 International Digital Economy Academy
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// For inquiries, you can contact us via e-mail at jichuruanjian@idea.edu.cn.

//! Post-processes a C file generated by `moonc link-core` for the native backend
//! to add wrapper functions for export aliases.
//!
//! This is a workaround for the moonc native backend ignoring the alias part
//! of `exported_functions` entries (e.g. "hello:my_hello"). The moonc compiler
//! generates a forward declaration using the mangled name but does not emit
//! an alias wrapper. This tool parses the generated C file, finds the forward
//! declarations matching the exported function names, and appends thin wrapper
//! functions that call through to the mangled names.

use std::path::PathBuf;

use anyhow::Context;

/// Subcommand: `moon tool postprocess-native-exports <c-file> <exported-functions>`
#[derive(Debug, clap::Parser)]
pub(crate) struct PostprocessNativeExports {
    /// Path to the C file generated by `moonc link-core`.
    pub c_file: PathBuf,

    /// Comma-separated list of exported functions.
    /// Each entry is either "funcname:alias" or "funcname".
    /// Only entries with aliases are processed.
    pub exported_functions: String,
}

/// An export entry with an alias.
struct AliasedExport {
    /// The original function name (before mangling).
    func_name: String,
    /// The alias name to expose.
    alias: String,
}

/// Build the mangled name suffix pattern for a given function name.
///
/// MoonBit's name mangling escapes `_` as `__`, then prefixes the escaped
/// name with its length. For example:
/// - `hello` -> `5hello`
/// - `do_nothing` -> `12do__nothing`
fn mangled_suffix(func_name: &str) -> String {
    let escaped = func_name.replace('_', "__");
    let len = escaped.len();
    format!("{}{}", len, escaped)
}

pub(crate) fn run_postprocess_native_exports(cmd: PostprocessNativeExports) -> anyhow::Result<i32> {
    // Parse exported functions, keeping only those with aliases
    let aliases: Vec<AliasedExport> = cmd
        .exported_functions
        .split(',')
        .filter_map(|entry| {
            let entry = entry.trim();
            if entry.is_empty() {
                return None;
            }
            let (func_name, alias) = entry.split_once(':')?;
            Some(AliasedExport {
                func_name: func_name.to_string(),
                alias: alias.to_string(),
            })
        })
        .collect();

    if aliases.is_empty() {
        return Ok(0);
    }

    let content = std::fs::read_to_string(&cmd.c_file)
        .with_context(|| format!("Failed to read C file: {}", cmd.c_file.display()))?;

    let mut wrappers = Vec::new();

    for export in &aliases {
        let suffix = mangled_suffix(&export.func_name);
        // Match forward declarations like:
        //   int32_t _M0FP...5hello(void);
        //   moonbit_string_t _M0FP...5greet(moonbit_string_t);
        //   void _M0FP...12do__nothing(void);
        //
        // The pattern captures:
        //   1. Return type (e.g. "int32_t", "void", "moonbit_string_t")
        //   2. Mangled function name (e.g. "_M0FP...5hello")
        //   3. Parameter list (e.g. "void", "moonbit_string_t", "int32_t, moonbit_string_t")
        let pattern = format!(
            r"^(\w[\w\s\*]*?)\s+(_M0FP\w*{})\s*\((.*?)\)\s*;",
            regex::escape(&suffix)
        );
        // Use multiline mode so ^ matches start of each line
        let re = regex::RegexBuilder::new(&pattern)
            .multi_line(true)
            .build()
            .with_context(|| {
                format!("Failed to compile regex for function: {}", export.func_name)
            })?;

        if let Some(caps) = re.captures(&content) {
            let return_type = caps.get(1).unwrap().as_str().trim();
            let mangled_name = caps.get(2).unwrap().as_str();
            let params_str = caps.get(3).unwrap().as_str().trim();

            let is_void_return = return_type == "void";

            // Build the wrapper function
            let wrapper = if params_str == "void" || params_str.is_empty() {
                // No parameters
                let call = format!("{}()", mangled_name);
                let body = if is_void_return {
                    format!("  {};", call)
                } else {
                    format!("  return {};", call)
                };
                format!("{} {}(void) {{\n{}\n}}", return_type, export.alias, body)
            } else {
                // Has parameters: generate arg0, arg1, ... names
                let param_types: Vec<&str> = params_str.split(',').map(|s| s.trim()).collect();
                let formal_params: Vec<String> = param_types
                    .iter()
                    .enumerate()
                    .map(|(i, ty)| format!("{} arg{}", ty, i))
                    .collect();
                let actual_args: Vec<String> = (0..param_types.len())
                    .map(|i| format!("arg{}", i))
                    .collect();
                let call = format!("{}({})", mangled_name, actual_args.join(", "));
                let body = if is_void_return {
                    format!("  {};", call)
                } else {
                    format!("  return {};", call)
                };
                format!(
                    "{} {}({}) {{\n{}\n}}",
                    return_type,
                    export.alias,
                    formal_params.join(", "),
                    body
                )
            };

            wrappers.push(wrapper);
        }
        // If no match found, silently skip (safe for future moonc versions)
    }

    if wrappers.is_empty() {
        return Ok(0);
    }

    // Append wrappers at the end of the file.
    //
    // In moonc's native C output, the user's exported functions and
    // `moonbit_init()` are placed AFTER the `#ifdef __cplusplus` / `}`
    // / `#endif` block (which closes the `extern "C"` wrapper for the
    // runtime helpers). The wrappers must come after these definitions
    // so that the mangled names are already declared.
    let wrapper_block = format!(
        "\n/* Export alias wrappers (generated by moon tool postprocess-native-exports) */\n{}\n",
        wrappers.join("\n\n")
    );

    let new_content = format!("{}{}", content, wrapper_block);

    std::fs::write(&cmd.c_file, new_content)
        .with_context(|| format!("Failed to write C file: {}", cmd.c_file.display()))?;

    Ok(0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_mangled_suffix() {
        assert_eq!(mangled_suffix("hello"), "5hello");
        assert_eq!(mangled_suffix("greet"), "5greet");
        assert_eq!(mangled_suffix("do_nothing"), "11do__nothing");
        assert_eq!(mangled_suffix("get_value"), "10get__value");
        assert_eq!(mangled_suffix("a"), "1a");
        assert_eq!(mangled_suffix("a_b"), "4a__b");
    }

    #[test]
    fn test_parse_aliases() {
        let input = "hello:my_hello,greet:my_greet,do_nothing";
        let aliases: Vec<AliasedExport> = input
            .split(',')
            .filter_map(|entry| {
                let entry = entry.trim();
                if entry.is_empty() {
                    return None;
                }
                let (func_name, alias) = entry.split_once(':')?;
                Some(AliasedExport {
                    func_name: func_name.to_string(),
                    alias: alias.to_string(),
                })
            })
            .collect();

        assert_eq!(aliases.len(), 2);
        assert_eq!(aliases[0].func_name, "hello");
        assert_eq!(aliases[0].alias, "my_hello");
        assert_eq!(aliases[1].func_name, "greet");
        assert_eq!(aliases[1].alias, "my_greet");
    }

    #[test]
    fn test_wrapper_generation_no_args() {
        let c_content = r#"
#include <stdint.h>
int32_t _M0FPkawaz0Ahello0Amain0A5hello(void);
void _M0FPkawaz0Ahello0Amain0A12do__nothing(void);
#ifdef __cplusplus
}
#endif
"#;

        // Test that we can match the forward declarations
        let suffix = mangled_suffix("hello");
        let pattern = format!(
            r"^(\w[\w\s\*]*?)\s+(_M0FP\w*{})\s*\((.*?)\)\s*;",
            regex::escape(&suffix)
        );
        let re = regex::RegexBuilder::new(&pattern)
            .multi_line(true)
            .build()
            .unwrap();
        let caps = re.captures(c_content).unwrap();
        assert_eq!(caps.get(1).unwrap().as_str().trim(), "int32_t");
        assert_eq!(
            caps.get(2).unwrap().as_str(),
            "_M0FPkawaz0Ahello0Amain0A5hello"
        );
        assert_eq!(caps.get(3).unwrap().as_str().trim(), "void");
    }

    #[test]
    fn test_wrapper_generation_with_args() {
        let c_content = r#"
moonbit_string_t _M0FPkawaz0Ahello0Amain0A5greet(moonbit_string_t);
#ifdef __cplusplus
}
#endif
"#;

        let suffix = mangled_suffix("greet");
        let pattern = format!(
            r"^(\w[\w\s\*]*?)\s+(_M0FP\w*{})\s*\((.*?)\)\s*;",
            regex::escape(&suffix)
        );
        let re = regex::RegexBuilder::new(&pattern)
            .multi_line(true)
            .build()
            .unwrap();
        let caps = re.captures(c_content).unwrap();
        assert_eq!(caps.get(1).unwrap().as_str().trim(), "moonbit_string_t");
        assert_eq!(
            caps.get(2).unwrap().as_str(),
            "_M0FPkawaz0Ahello0Amain0A5greet"
        );
        assert_eq!(caps.get(3).unwrap().as_str().trim(), "moonbit_string_t");
    }
}
